# Generated by Django 6.0.3 on 2026-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=20),
        ),
    ]
